using AutoMapper;
using Ticketa.Core.DTOs;
using Ticketa.Core.Entities;

namespace Ticketa.Core.Mapping
{
  public class MovieProfile : Profile
  {
    public MovieProfile()
    {
      CreateMap<TmdbMovieDto, Movie>()
        .ForMember(dest => dest.Id, opt => opt.Ignore()) // Id is generated by the database
        .ForMember(dest => dest.ImportedAt, opt => opt.Ignore())
        .ForMember(dest => dest.ReleaseDate, opt => opt.MapFrom(src => ParseDate(src.ReleaseDate)));
    }

    private static DateTime ParseDate(string? dateStr)
    {
      return DateTime.TryParse(dateStr, out var d) ? d : DateTime.MinValue;
    }
  }
}
